### ISSUE TITLE
小白还是没设置好

### ISSUE THREAD

**Issue by Lawrencelee0418** [Chaoyingz/lixinger#2]
step 1. pip install lixinger
OK
step 2.  export LIXINGER_TOKEN="my token"
就报错了
export LIXINGER_TOKEN="my token"
           ^
SyntaxError: invalid syntax

能否 像tushare 一样，step 清晰一点，谢谢！

**Comment by Chaoyingz** [comment]
我更新了 readme，windows 可以使用 `set LIXINGER_TOKEN="my token"` 来设置环境变量，或者使用配置文件来设置。
